image:
  override: '' # if defined, this value is used as the canonical image name ("{image_repo}{image_name}:{tag}")
  tag: v1.0.2-eksbuild.4  # this is the default image tag. It might be overwritten at runtime
  containerRegistry: '' # this gets overriden at runtime with the correct Docker Image Registry
  name: aws-network-sonar-agent # this determines the ecr folder to look for in the target ecr registry

clusterRole:
  name: aws-network-flow-monitor-agent-role

clusterRoleBinding:
  name: aws-network-flow-monitor-agent-role-binding

serviceAccount:
  name: aws-network-flow-monitor-agent-service-account

daemonSet:
  name: aws-network-flow-monitor-agent

# Common labels to add to all network-flow-monitor-agent resources. Evaluated as a template.
additionalLabels: {}

# Useful parameters that provide flexibility to customers
podLabels: {}
podAnnotations: {}
tolerations: []

# allow user to change the internal addon name labels
nameOverride: ""

env:
  RUST_LOG: info

resources:
  limits:
    cpu: 100m
    memory: 200Mi
  requests:
    cpu: 50m
    memory: 100Mi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
          # Don't schedule on special compute types
        - key: eks.amazonaws.com/compute-type
          operator: NotIn
          values:
            - fargate
            - hybrid
          # Only schedule on amd64 nodes
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
            - arm64

priorityClassName: ""